### ISSUE TITLE
Missing SYSTEM_TIME property in default_api_template.xml file

### ISSUE THREAD

**Issue by niranRameshPeiris** [wso2/api-manager#1351] opened 2023-01-30 09:04 UTC
### Description

We have enabled the default API by using the below confirmations. 
```
[apim.global_handlers.properties]
skip_default_api_handler = true
```
Then we collected correlation logs after invoking a default API URL.
Example: 
>  Version API URL: /newapi/v1/test
Default APO URL: /newapi/test

When we invoke the default API instead of the Version API, in the correlation logs we can see the HTTP log line as below. 
```
2023-01-30 11:06:19,883|71c3e1b8-0bfb-41d7-b4fe-afa20f36153e|PassThroughMessageProcessor-13|**1675056979835**|HTTP|admin--testapi|GET|/testapi/*|testapi|Bearer eyJ4NXQiOiJNell4TW1Ga....
```
As you can see, instead of time in milliseconds it will print the timestamp. It was identified that this is happening due to a missing property in synapse configurations. 

### Steps to Reproduce

1. Add the below configuration and start the APIM server. 
```
[apim.global_handlers.properties]
skip_default_api_handler = true
```
2. Create a versioned API.
3. Enable correlation logs.
4. Invoke the API and collect logs.

### Affected Component

APIM

### Version

3.2.0

**Comment by HeshanSudarshana** [comment] 2023-02-13 03:46
Closing since this issue is not reproducible in the master branch.

**Closed by HeshanSudarshana** 2023-02-13 03:46 UTC
Labels: Type/Bug, Affected/APIM-3.2.0
