### ISSUE TITLE
Removal of Jaggery.js from APIM Apps and replace it with another server side language

### ISSUE THREAD

**Issue by DinithHerath** [wso2/api-manager#213] opened 2022-06-22 04:27 UTC
### Problem

- **jaggery.js** has great advantages as a framework, but currently it is not in the active stage of development and maintenance.
- Therefore there is an ample need to remove the jaggery component from the APIM apps and replace it with a language which is more closer to server-side while having the react component as the handler of the client side.

### Solution

- The most common method for writing the server side applications for web applications related to Java is the usage of the JSP and Java Servlets. JSP has access to the entire family of Java APIs, including the JDBC API to access enterprise databases and so on. 
- Also the Servlets allow the frontend applications to pass the data through the context as well.
- A quick comparison between **jaggery.js** and **JSP with JAVA servlet** are mentioned below.

  | Jaggery.js | JSP and Servlet |
  | :------------: |:---------------:| 
  | Uses js as the based language  | Uses java as based language |
  | Uses abstraction layer to communicate with native Java execution | Allows to directly execute the java codes within the HTML |
  | Client side should be separated from jaggery component | Can be used to insert the Java into HTML pages as well |
  | Uses Java abstraction layer to communicate | Servlet allows to process post, get request method on server side |

### Affected Component

APIM

### Version

4.2.0

### Implementation

- The method for migration is twofold. 
- First the initial files such as the files that do not have any external dependencies will be migrated in a separate project. This will allow the migration to be easier and to examine the various methods in the JSP and servlets in the migration process. 
- Secondly, the whole codebase for jaggery apps will be migrated to **JSP and JAVA Servlets** context.
- The task will be executed in following sub tasks.

**Devportal Migration**
  - [x] #222
  - [x] #593
  - [x] #302
  - [x] #303
  - [x] #304
 
**Publisher Portal Migration**
  - [x] #517 
  - [x] #518
  - [x] #519 
 
**Admin Portal Migration**
  - [x] #538
  - [x] #536
  - [x] #537

**Finalising**
  - [x] #305
  - [x] #593
  - [x] #419

**Comment by tharikaGitHub** [comment] 2022-10-28 06:07
Closing as the issue is completed.

**Closed by tharikaGitHub** 2022-10-28 06:07 UTC
Labels: Type/Improvement, Priority/Normal, Component/APIM, Affected/APIM-4.1.0
