### ISSUE TITLE
Support separate client side MTLS for product and sandbox

### ISSUE THREAD

**Issue by dushaniw** [wso2/api-manager#2433] opened 2024-01-29 05:47 UTC
### Problem

API can be secured with MTLS and there are can be two different certificates for production and sandbox environments. Current MTLS feature only supports having a single certificate, internally we consider it as production.

### Solution

Supporting uploading and managing MTLS separately for production and sandbox.

### Affected Component

APIM

### Version

5.x.x

**Comment by RusJaI** [comment] 2024-05-21 04:33
### Update [2024-05-16]

After analysing this issue, it was identified that this involves changes in DB schema, hence this feature can be delivered in a new release.

created the doc : https://docs.google.com/document/d/1E1BySLHAuXNNWi3WHvhTzvkCaJYMsqD2Nfwan1313N4/edit?usp=sharing

**Comment by RusJaI** [comment] 2024-05-22 06:01
### Update [2024-5-21]
Designed the UI for uploading certificates and modified the design outline doc

<img width="1484" alt="Screenshot 2024-05-21 at 11 19 17" src="https://github.com/wso2/api-manager/assets/48326709/527bf32e-f6c9-44a8-beb3-1a021cd55257">

**Comment by RusJaI** [comment] 2024-05-22 06:01
### Update [2024-05-22]
Initiated the email thread : 

> [Architecture] Support separate client side MTLS for production and sandbox endpoints in API Manager

**Comment by RusJaI** [comment] 2024-05-27 07:35
### Update [2024-05-27]
Had the design review today.
Started working on the suggested modifications.

**Comment by RusJaI** [comment] 2024-05-29 16:33
### Update [2024-05 28 and 29]

Worked on the backend implementation 
This includes database and API level changes related to client-certificates, 
including the key type in client certificate objects to access in MutualSSLAuthenticator.

PR : https://github.com/wso2/carbon-apimgt/pull/12455

Left to do : 
- Need to verify the keyType that should be provided for handleNoAuthentication() flow
- Need to test the backend implementation thoroughly including the behaviours with certificate chains
- The changes affects the existing integration tests. Need to fix them
- Check the possibilities to add new tests.

**Comment by RusJaI** [comment] 2024-05-31 12:19
### Update [2024-05-31]
Had a discussion with the previously identified scenario : When both MTLS and Application level security type like OAuth2 is selected as mandatory, and invoke the gateway endpoint with bearer token for Sandbox and client certificate uploaded for production type it returns a 200 response. This was mentioned as somewhat expected, and discussed to specifically mention in the documentation about it.

Worked on manual testing on other affected flows.

**Comment by RusJaI** [comment] 2024-06-04 08:36
### Update [2024-06-3, 4]

Created a QA Doc and Performed manual testing.
Scheduled a discussion to verify the outcomes of the manual tests.

Putting the rest of the work on-hold due to another urgent RnD allocation from today onwards.

**Comment by RusJaI** [comment] 2024-06-22 11:38
### Update [2024-06-20, 21]

Modified the integration tests, covering the new behaviour
Modified the UI tests.
Fixed some issues identified in UI, while  executing the tests.

**Comment by RusJaI** [comment] 2024-06-26 08:35
### Update [2024-06-25,26]
Worked on an issue identified after the QA doc was reviewed.

**Comment by RusJaI** [comment] 2024-06-26 08:36
### Update [2024-06-25,26]
Worked on an issue identified after the QA doc was reviewed.

**Comment by RusJaI** [comment] 2024-06-26 09:24
Please find the PRs related to the feature as follows : 
| Description| PR |
|--| --|
|UI Implementation and UI tests | https://github.com/wso2/apim-apps/pull/706 |
|Backend Implementation and Integration tests. |  https://github.com/wso2/carbon-apimgt/pull/12455, https://github.com/wso2/product-apim/pull/13503 |
| Documentation | https://github.com/wso2/docs-apim/pull/8077 |

**Comment by RusJaI** [comment] 2024-06-28 09:20
As per the decision to facilitate two production and sandbox certs with same alias, the existing REST API have to be marked as deprecated and a new REST API should be introduced.
Started working on the proposed modifications.

**Comment by mohanvive** [comment] 2024-07-03 22:10
@RusJaI With this change, do we have an option to disable MTLS for sandbox endpoint while keep it enable for production endpoint?

**Comment by RusJaI** [comment] 2024-07-04 08:12
> @RusJaI With this change, do we have an option to disable MTLS for sandbox endpoint while keep it enable for production endpoint?

@mohanvive what is expected from this feature is when MTLS enabled user can upload certificates for production and sandbox key types. 
Let['s consider a scenario where only transport level security is enabled and we've chosen MTLS there : 
When API is invoked using a certificate, it checks the key type that certificate belong to, based on the uploaded certificates under production and sandbox key types. 
For example if the key type is SANDBOX, the SANDBOX endpoint is invoked.

**Comment by mohanvive** [comment] 2024-07-04 13:55
@RusJaI Thanks for the explanation. I have some further queries. 

1. Do we have an option to upload certificate only for the production endpoint without sandbox.
2. If (1) is possible, then what is the expected behaviour?

**Comment by RusJaI** [comment] 2024-07-04 14:13
> @RusJaI Thanks for the explanation. I have some further queries.
> 
> 1. Do we have an option to upload certificate only for the production endpoint without sandbox.

Yes. We can select, for which endpoint type we are uploading the certificate. There you can upload certificate only for the production endpoint.
> 2. If (1) is possible, then what is the expected behaviour?

When invoking the API, if you are providing one of the certificates that you've uploaded under production certificates, the production endpoint should be invoked. 
Else (if the certificate you are providing during the invocation is not among the certificates you've uploaded for endpoint types) there will be an authentication failure.

**Comment by RusJaI** [comment] 2024-07-05 07:50
### Update [2024-07-04]

Did the frontend and backend implementation to facilitate the same alias for production and sandbox certificates.

This effort involved the following :
- Make changes in DB scripts and data layers to include the key type in composite primary key.
- Change the directory structure of storing the client certificates
- Modify the key format in trust store entries
- Deprecate the existing client certificate APIs and introduce new set of APIs (/client-cert/{keyType}/)
- Related frontend changes (methods to invoke APIs for production and sandbox types separately in component functions and api client, maintain separate alias lists for operations related to endpoint certs and client certs,remove usage button for client certificates.)

**Comment by RusJaI** [comment] 2024-07-05 08:04
### Update [2024-07-05]

Following scenarios were tested : 
-Add/ delete client certificates
-Add /delete endpoint certificates
-Invoke endpoints when MTLS enabled in following combinations : 
  1. MTLS - mandatory with no application level security selected
  2. MTLS mandatory and basic auth optional
  3. MTLS optional and basic auth mandatory
  
Identified an authentication failure for optional optional scenario. Created issue : https://github.com/wso2/api-manager/issues/2988

**Comment by RusJaI** [comment] 2024-07-11 09:47
Hi all,
The implementation of this task is done. PRs are under review. 
Following tasks which are left to do : 
- [ ] Check the integration tests with newly added changes
- [ ] Update Documentation

**Closed** 2024-07-29 12:44 UTC
Labels: Type/New Feature, Component/APIM
