### ISSUE TITLE
UI styling issues in global policies and scopes listing pages

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/api-manager#2543] opened 2024-03-01 06:39 UTC
### Description

There are several styling issues in global policies and scopes listing pages
- Margins are not correctly set
- Action button colour 

---
### Global policies listing page (4.3.0-m1)

![m1-gp](https://github.com/wso2/api-manager/assets/55122994/87262eb4-736d-4181-9c25-d736ac1d6f94)

### Global policies listing page (pre-alpha)

![alpha-gp](https://github.com/wso2/api-manager/assets/55122994/73f0b1af-5c4c-405f-ae17-08d68f38f543)

---

Same kind of issues can be observed in scopes listing page as well

### Steps to Reproduce

1. Navigate to publisher portal
2. Go to global policies page and create a new global policy
3. Go to global policies listing page

### Affected Component

APIM

### Version

4.3.0

**Comment by lasanthaS** [comment] 2024-03-13 10:02
Duplicate of https://github.com/wso2/api-manager/issues/2626. Resolved with https://github.com/wso2/apim-apps/pull/596. Hence closing.

**Closed by lasanthaS** 2024-03-13 10:02 UTC
Labels: Type/Bug, Priority/High, Component/APIM, React-UI, 4.3.0, 4.3.0-alpha, BugFixing
