### ISSUE TITLE
Applications can not be edited or deleted by own user with case sensitive username

### ISSUE THREAD

**Issue by Prabhashi** [wso2/api-manager#546] opened 2022-08-01 12:17 UTC
### Description

Application in devportal can be edited or deleted by own user with case sensitive username

### Steps to Reproduce

Update level 3.0.0.91 and the latest. (96):

- Created a user test.COM and logged in to the devportal with this user.
- The default application will be created for this user. The owner is test.COM
- Then, logged out from this user and logged in as test.com (all simple).
- Can not edit or delete Applications.

The issue is not there in GA pack of APIM 3.0.0.

### Affected Component

APIM

### Version

3.0.0

**Comment by ashera96** [comment] 2022-08-02 11:20
Duplicate of [1]. Public fix for this issue is already done.

1. https://github.com/wso2/product-apim/issues/12152

**Comment by ashera96** [comment] 2022-08-02 14:44
Closing since the public fix is already available.

**Closed by ashera96** 2022-08-02 14:44 UTC
Labels: Type/Bug, Priority/Normal, Resolution/Duplicate, Component/APIM, Affected/APIM-3.0.0
