### ISSUE TITLE
The Add Header Policy has a limited number of characters

### ISSUE THREAD

**Issue by TomasWso2** [wso2/api-manager#2724] opened 2024-03-27 20:55 UTC
### Problem

Cannot add "Add header" v2 policy to a resource with more than 1024 characters.

The policy is not saved and i get the following error:
ERROR - ApisApiServiceImpl Error while updating the API : 8bf8fc23-2b5a-4dd9-a3e7-a8889fe7082b - Error while adding api level policies for API : 8bf8fc23-2b5a-4dd9-a3e7-a8889fe7082b
org.wso2.carbon.apimgt.api.APIManagementException: Error while adding api level policies for API : 8bf8fc23-2b5a-4dd9-a3e7-a8889fe7082b
        at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException_aroundBody308(ApiMgtDAO.java:6998) ~[org.wso2.carbon.apimgt.impl_9.20.74.253.jar:?]
        at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.handleException(ApiMgtDAO.java:6995) ~[org.wso2.carbon.apimgt.impl_9.20.74.253.jar:?]
        ...
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "PARAMETERS CHARACTER VARYING(1024)": "'{""headerName"":""asdasdasdsaasdsadasdsaasdasdasdsaasdsadasdsaasdasdasdsaasdsadasd... (3730)"; SQL statement:
INSERT INTO AM_API_OPERATION_POLICY_MAPPING  (URL_MAPPING_ID, POLICY_UUID, DIRECTION, PARAMETERS, POLICY_ORDER)  VALUES (?,?,?,?,?) [22001-210]
        at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1269) ~[h2_2.1.210.wso2v1.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor253.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118) ~[jdbc-pool_9.0.58.wso2v1.jar:?]
        at com.sun.proxy.$Proxy54.executeBatch(Unknown Source) ~[?:?]
        at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addAPIPoliciesMapping_aroundBody950(ApiMgtDAO.java:19652) ~[org.wso2.carbon.apimgt.impl_9.20.74.253.jar:?]
        ... 67 more
		
PARAMETERS column in AM_API_OPERATION_POLICY_MAPPING tables has a char limit of 1024.

### Solution

Increase the size of the PARAMETERS column in AM_API_OPERATION_POLICY_MAPPING tables or add a clear limit.

### Affected Component

APIM

### Version

wso2am-4.1.0-143

**Comment by RakhithaRR** [comment] 2024-07-11 06:05
Closing this since this was determined as not a bug

**Closed by RakhithaRR** 2024-07-11 06:05 UTC
Labels: Type/Improvement, Missing/Component
