### ISSUE TITLE
Oracle specific sql query issues after migrating to IS 5.11.0 from IS-5.10.0

### ISSUE THREAD

**Issue by shilmyhasan** [wso2/api-manager#679] opened 2022-08-26 05:35 UTC
### Description

Sql query not properly ended exception is thrown while logging into carbon console, after migrating from IS 5.10.0 to 5.11.0.  BUt this appears to be a product bug as the same error could be reproduced even when we run the query at [1] directly in oracle.

[1]- https://github.com/wso2/carbon-identity-framework/blob/master/components/configuration-mgt/org.wso2.carbon.identity.configuration.mgt.core/src/main/java/org/wso2/carbon/identity/configuration/mgt/core/dao/impl/ConfigurationDAOImpl.java#L326

### Steps to Reproduce

Migrate to  WSO2 IS 5.11.0 from 5.10.0 as resident key manager for WSO2 APIM with Oracle.

### Affected Component

APIM

### Version

4.0.0

**Comment by dushaniw** [comment] 2022-09-21 08:40
could not reproduce. hence closing.

**Closed by dushaniw** 2022-09-21 08:40 UTC
Labels: Type/Bug, Priority/Normal, Resolution/Cannot Reproduce, Affected/APIM-4.0.0, Area/Migration
