### ISSUE TITLE
Consumer key input field label is on top of the field content

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/api-manager#2629] opened 2024-03-13 07:38 UTC
### Description

When provisioning an application using existing keys, the consumer key input field label is on top of the field content.

![Screenshot 2024-03-13 at 12 31 18](https://github.com/wso2/api-manager/assets/25485783/394f5340-44ec-475f-8ab8-466905a85620)

### Steps to Reproduce

1. Configure a Third party KM
2. Add existing oauth keys to provision an application
3. The consumer key input field label will be on top of the field content

### Affected Component

APIM

### Version

4.3.0-alpha

**Comment by lasanthaS** [comment] 2024-03-26 11:02
This issue couldn't reproduce in the latest pack. Hence closing the issue.

**Closed by lasanthaS** 2024-03-26 11:02 UTC
Labels: Type/Bug, Type/UX, Resolution/Cannot Reproduce, Component/APIM, 4.3.0-alpha, Affected/APIM-4.3.0, BugFixing
