### ISSUE TITLE
[APIM][4.0.0]Filtering for the Subscriptions list per page is not working properly

### ISSUE THREAD

**Issue by Thidasala** [wso2/api-manager#1216] opened 2023-01-11 06:46 UTC
### Description

Filtering for the Subscriptions list per page is not working properly in publisher portal

### Steps to Reproduce

1. Login in Publisher portal
2. Select an API which has Subscribers more than 15 or 20
3. Select the API and click on "Subscriptions" option
4. By Default, per page only the first 5 Subscribers will be listed
5. Change tha value from 5 to 25 per page from the Drop down list

Expected: Up to 25 Sbuscription sper page should be displayed
Even after selecting 25, only 10 Subscriptions of the API is displayed and unable to see the other subscriptions

### Affected Component

APIM

### Version

4.0.0

**Comment by IsuruMaduranga** [comment] 2023-01-17 09:27
Hi @Thidasala,

The issue is not reproducible in the latest build of APIM. Hence closing the issue.

Thanks,
Isuru

**Closed by IsuruMaduranga** 2023-01-17 09:27 UTC
Labels: Type/Bug, Priority/Normal, Affected/APIM-4.0.0
