### ISSUE TITLE
Change the existing Docker Image name in SI 4.2.0-RC to wso2/wso2si:4.2.0

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#1596] opened 2023-03-10 10:15 UTC
### Problem

<img width="815" alt="image" src="https://user-images.githubusercontent.com/38649090/224289432-0a6298a2-c4c6-41e9-b9f3-132687946348.png">

Right now the default name is wso2/wso2si:4.1.0 and since this is 4.2.0, we need to change that. 

### Solution

Change the default docker name from wso2/wso2si:4.1.0 to wso2/wso2si:4.2.0

### Affected Component

SI

### Version

4.2.0-RC

**Comment by PasanT9** [comment] 2023-03-10 10:23
Ack. Will check and update.

**Comment by rmsamitha** [comment] 2023-03-15 08:22
Might need to change the PR https://github.com/wso2/carbon-analytics/pull/1998 based on where the docker images will be hosted (dockerhub or private wso2 docker repo )

**Comment by rmsamitha** [comment] 2023-03-27 11:36
This fix should be shipped in a next U2 update created on SI Tooling, since the fix is already merged.

**Comment by PasanT9** [comment] 2023-03-27 12:12
Follow the below steps to reproduce the issue.

1. Start SI Tooling 4.2.0.
2. Go to the editor (http://localhost:9390/editor)
3. Select a sample Siddhi application and save.
4. Go to Export > Export To Docker
5. Select the Siddhi application and proceed to Step 5 (Select Docker Image)
6. Select _Use an existing Docker image_

Notice that Docker image is wso2/wso2si:4.1.0. This need to be changed to **wso2/wso2si:4.2.0**

**Comment by YasasRangika** [comment] 2024-01-15 19:49
Public fix PR: https://github.com/wso2/carbon-analytics/pull/1998 has already been merged.

**Closed by YasasRangika** 2024-01-15 19:49 UTC
Labels: Type/Bug, Component/SITooling, 4.2.0-RC
