### ISSUE TITLE
Status not shown when Choreo return 504 for API Chat

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/api-manager#2741] opened 2024-03-29 04:05 UTC
### Description

<img width="1670" alt="Screenshot 2024-03-29 at 09 33 58" src="https://github.com/wso2/api-manager/assets/25485273/dd1de460-9f1b-4345-8209-fa2700add8f0">

### Steps to Reproduce

Try out the API Chat

### Affected Component

APIM

### Version

4.3.0

**Comment by ashera96** [comment] 2024-04-01 06:25
UI error rendering issue is fixed via https://github.com/wso2/apim-apps/pull/663/commits/9119c0bd2700fca8fe68d80d640e55341306cb26 under the PR [1]

1. https://github.com/wso2/apim-apps/pull/663

**Comment by ashera96** [comment] 2024-04-01 07:30
Since the wait is already 1 min, let's not increase this timeout any further. There already exists a retry logic on timeout getting hit (the wait is 15 seconds).

**Comment by ashera96** [comment] 2024-04-01 09:36
Closing as proper error handling is now added to the UI level. If the timeout issue reproduces at a larger scale we can reopen and investigate further into the issue.

**Closed by ashera96** 2024-04-01 09:36 UTC
Labels: Type/Bug, Component/APIM, 4.3.0, 4.3.0-beta, Affected/APIM-4.3.0, BugFixing
