### ISSUE TITLE
Regex does not working for avoiding the JavaScript Injection

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#2549] opened 2024-03-01 11:04 UTC
### Description

The provided regex pattern in the documentation [1] for detecting the JavaScript injections is not working.

[1] - https://apim.docs.wso2.com/en/latest/deploy-and-publish/deploy-on-gateway/api-gateway/threat-protectors/regular-expression-threat-protection-for-api-gateway/#:~:text=%3C%5Cs*script%5Cb%5B%5E%3E%5D*%3E%5B%5E%3C%5D%2B%3C%5Cs*/%5Cs*script%5Cs*%3E

### Steps to Reproduce

Attach the following sequence to the request flow of the API.

Please find the sequence below.

```
<sequence xmlns="http://ws.apache.org/ns/synapse" name="regex_policy">
    <log level="custom">
        <property name="IN_MESSAGE" value="Regular_expression_policy"/>
    </log>
    <property name="threatType" expression="get-property('threatType')" value="JavaScript-Injection"/>
    <property name="regex" expression="get-property('regex')" value="<\s*script\b[^>]*>[^<]+<\s*/\s*script\s*>"/>
    <property name="enabledCheckBody" expression="get-property('checkBodyEnable')" value="true"/>
    <property name="enabledCheckHeaders" expression="get-property('enabledCheckHeaders')" value="true"/>
    <property name="enabledCheckPathParams" expression="get-property('enabledCheckPathParams')" value="true"/>
    <class name="org.wso2.carbon.apimgt.gateway.mediators.RegularExpressionProtector"/>
</sequence>
```

### Affected Component

APIM

### Version

4.2.0

**Comment by RakhithaRR** [comment] 2024-07-11 06:01
According to the internal discussion the patch was put on hold as it it not a bug. Hence closing this issue.

**Closed by RakhithaRR** 2024-07-11 06:01 UTC
Labels: Type/Bug, Affected/APIM-4.2.0
