### ISSUE TITLE
Publisher portal login page directs to error page when click on "Forgot Password"

### ISSUE THREAD

**Issue by RusJaI** [wso2/api-manager#2477] opened 2024-02-14 09:26 UTC
### Description

When click on the "Forgot password ?" link at the publisher login page of API Manager , it shows that "Page not working" with a 400 response code. When enter the same url next time on the browser it navigates to the intended page.
When checking the diff of the headers in the above 2 attempts, it seems that the "Referer" header value is missing in the initial attempt.

### Steps to Reproduce

1. Go to the login page of the API Manager Publisher portal
2. click on "Forgot password ?"
3. you'll get a "Page not working" view with 400 response status code
4. when click enter on the same url, you'll be navigated to the intended forget password page 

### Affected Component

APIM

### Version

4.3.0-m1

### Environment Details (with versions)

Mac OS (M1)

**Comment by tharikaGitHub** [comment] 2024-03-03 06:46
Closing as the issue is not reproduced in the latest pack.

**Closed by tharikaGitHub** 2024-03-03 06:46 UTC
Labels: Type/Bug, Component/APIM, 4.3.0, 4.3.0-alpha
