### ISSUE TITLE
Error when converting the client certificate in the request 

### ISSUE THREAD

**Issue by ChinthakaJ98** [wso2/api-manager#1123] opened 2022-12-13 11:55 UTC
### Description

When trying to convert the client certificate in the request at the time of building the message context, the ServerWorker encounters an error due to the usage of javax.security.cert.X509Certificate.getInstance [1] method which was deprecated since Java 9 and then removed in Java 17. 

[1] https://github.com/wso2/wso2-synapse/blob/master/modules/transports/core/nhttp/src/main/java/org/apache/synapse/transport/passthru/ServerWorker.java#L559

### Steps to Reproduce

Execute an API request which requires a client certificate validation

### Affected Component

APIM

### Version

4.2.0-M1

### Environment Details (with versions)

Java 17.0.5
synapse-nhttp-transport_2.1.7.wso2v314.jar

### Relevant Log Output

```shell
ERROR - ServerWorker Error while converting client certificate
javax.security.cert.CertificateException: Could not find class: java.lang.ClassNotFoundException: com/sun/security/cert/internal/x509/X509V1CertImpl
	at javax.security.cert.X509Certificate.getInst(X509Certificate.java:242) ~[?:?]
	at javax.security.cert.X509Certificate.getInstance(X509Certificate.java:208) ~[?:?]
	at org.apache.synapse.transport.passthru.ServerWorker.createMessageContext(ServerWorker.java:559) ~[synapse-nhttp-transport_2.1.7.wso2v314.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.<init>(ServerWorker.java:119) ~[synapse-nhttp-transport_2.1.7.wso2v314.jar:?]
	at org.apache.synapse.transport.passthru.ServerWorker.<init>(ServerWorker.java:142) ~[synapse-nhttp-transport_2.1.7.wso2v314.jar:?]
	at org.apache.synapse.transport.passthru.SourceHandler.requestReceived(SourceHandler.java:183) ~[synapse-nhttp-transport_2.1.7.wso2v314.jar:?]
	at org.apache.http.impl.nio.DefaultNHttpServerConnection.consumeInput(DefaultNHttpServerConnection.java:273) ~[httpcore-nio_4.4.15.wso2v1.jar:?]
	at org.apache.synapse.transport.http.conn.LoggingNHttpServerConnection.consumeInput(LoggingNHttpServerConnection.java:114) ~[synapse-nhttp-transport_2.1.7.wso2v314.jar:?]
	at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:82) ~[synapse-nhttp-transport_2.1.7.wso2v314.jar:?]
	at org.apache.synapse.transport.passthru.ServerIODispatch.onInputReady(ServerIODispatch.java:39) ~[synapse-nhttp-transport_2.1.7.wso2v314.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121) ~[httpcore-nio_4.4.15.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) ~[httpcore-nio_4.4.15.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) ~[httpcore-nio_4.4.15.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) ~[httpcore-nio_4.4.15.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) ~[httpcore-nio_4.4.15.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) ~[httpcore-nio_4.4.15.wso2v1.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) ~[httpcore-nio_4.4.15.wso2v1.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by rmsamitha** [comment] 2023-02-25 05:49
As per @Akila94 this is not reproduced in APIM vanilla pack. Only reproduced with OB accelerators.

**Comment by rmsamitha** [comment] 2023-02-25 05:56
In APIM the method "Certificate[] getClientCertsLatest()"[1] has been used instead of "X509Certificate[] getClientCerts() " [2] since the latter is deprecated.
These changes are introduced with [3].
As per offline conversation with @Akila94, he had tried this new method in OB code too, but the issue had been reproduced again with OB accelerators.

[1] -  https://github.com/wso2/carbon-apimgt/blob/7cb37bf0863b2a07464c5de7af64536b173c8827/components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/RequestContextDTO.java#L96
[2] - https://github.com/wso2/carbon-apimgt/blob/7cb37bf0863b2a07464c5de7af64536b173c8827/components/apimgt/org.wso2.carbon.apimgt.common.gateway/src/main/java/org/wso2/carbon/apimgt/common/gateway/dto/RequestContextDTO.java#L69)
[3] https://github.com/wso2/carbon-apimgt/pull/11405/commits

**Comment by tharikaGitHub** [comment] 2023-02-27 14:43
**Update**

A PR [1] is made fixing the issue.

***Next Steps :*** 

Need to test the flows to see if this works

[1] https://github.com/wso2/wso2-synapse/pull/2057

**Comment by tharikaGitHub** [comment] 2023-03-01 06:26
Reopening to track the synapse version upgrade in the respective products APIM and MI.

**Comment by tharikaGitHub** [comment] 2023-03-02 00:32
**Update** : 

There were few test failures which had to be looked into.

The following PRs upgrade the required versions.

- [ ] https://github.com/wso2/carbon-mediation/pull/1679
- [ ] https://github.com/wso2/micro-integrator/pull/2881
- [ ] https://github.com/wso2/micro-integrator/pull/2884
- [ ] https://github.com/wso2/carbon-apimgt/pull/11902
- [ ] https://github.com/wso2/product-apim/pull/13167

Thanks,
Tharika.

**Comment by tharikaGitHub** [comment] 2023-03-02 09:15
Closing as the task is completed.

**Closed by tharikaGitHub** 2023-03-02 09:15 UTC
Labels: Type/Bug, Priority/High, Component/APIM, 4.2.0-RC
