### ISSUE TITLE
[APIM 4.3.0-M1] Pack won't start up when OpenTelemetry is enabled

### ISSUE THREAD

**Issue by senthuran16** [wso2/api-manager#2427] opened 2024-01-26 11:13 UTC
### Description

Upon enabling OpenTelemetry [1] (I tested with Jaeger) as follows:
```
[apim.open_telemetry]
remote_tracer.enable = true
remote_tracer.name = "jaeger"
remote_tracer.hostname = "localhost"
remote_tracer.port = 14250
```

Startup of the pack fails with the following error:
```
[2024-01-26 16:32:41,159] ERROR - Framework FrameworkEvent ERROR
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration_aroundBody12(ServiceReferenceHolder.java:133) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration(ServiceReferenceHolder.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.<init>(InMemoryAPIDeployer.java:82) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.cleanDeployment_aroundBody6(GatewayStartupListener.java:175) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.cleanDeployment(GatewayStartupListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.completingServerStartup_aroundBody0(GatewayStartupListener.java:132) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.completingServerStartup(GatewayStartupListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyBefore(CarbonCoreServiceComponent.java:258) ~[?:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:162) ~[?:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:309) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118) ~[org.wso2.carbon.tenant.throttling.agent_4.9.20.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96) ~[org.wso2.carbon.tenant.throttling.agent_4.9.20.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
```

[1] https://apim.docs.wso2.com/en/latest/observe/api-manager/traces/monitoring-with-opentelemetry/#enabling-jaeger-tracing

### Steps to Reproduce

1. Enable OpenTelemetry as follows:
```
[apim.open_telemetry]
remote_tracer.enable = true
remote_tracer.name = "jaeger"
remote_tracer.hostname = "localhost"
remote_tracer.port = 14250
```
2. Start APIM pack and observe the error:
```
[2024-01-26 16:32:41,159] ERROR - Framework FrameworkEvent ERROR
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration_aroundBody12(ServiceReferenceHolder.java:133) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration(ServiceReferenceHolder.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.<init>(InMemoryAPIDeployer.java:82) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.cleanDeployment_aroundBody6(GatewayStartupListener.java:175) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.cleanDeployment(GatewayStartupListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.completingServerStartup_aroundBody0(GatewayStartupListener.java:132) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.completingServerStartup(GatewayStartupListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.28.221.jar:?]
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.notifyBefore(CarbonCoreServiceComponent.java:258) ~[?:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.completeInitialization(StartupFinalizerServiceComponent.java:162) ~[?:?]
	at org.wso2.carbon.core.internal.StartupFinalizerServiceComponent.serviceChanged(StartupFinalizerServiceComponent.java:309) ~[?:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.registerThrottlingAgent(ThrottlingAgentServiceComponent.java:118) ~[org.wso2.carbon.tenant.throttling.agent_4.9.20.jar:?]
	at org.wso2.carbon.throttling.agent.internal.ThrottlingAgentServiceComponent.activate(ThrottlingAgentServiceComponent.java:96) ~[org.wso2.carbon.tenant.throttling.agent_4.9.20.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.8.1.jar:?]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
```

### Affected Component

APIM

### Version

4.3.0.M1

**Comment by Lakith-Rambukkanage** [comment] 2024-02-13 10:18
After adding the config it was observed that the APIManagerConfigurationService is `set` and `unset` in APIHandlerServiceComponent several times. The null pointer occurs right after an unset call. 

```
2024-02-13 15:34:11,782]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:11,783]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,783]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,789]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:11,793]  INFO - BinaryDataReceiver Started Binary SSL Transport on port : 9711
[2024-02-13 15:34:11,794]  INFO - BinaryDataReceiver Started Binary TCP Transport on port : 9611
[2024-02-13 15:34:11,902]  INFO - ThriftServerStartupObserver  Thrift Data Receiver is disabled.
[2024-02-13 15:34:11,938]  INFO - InMemoryAPIDeployer [TRACK] trying to set gatewayArtifactSynchronizerProperties set in InMemoryAPIDeployer ===
[2024-02-13 15:34:11,944]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:11,944]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,944]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,950]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:11,952]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:11,953]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,953]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,961]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:11,963]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:11,964]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,964]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,969]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:11,971]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:11,972]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,972]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,978]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:11,993]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:11,994]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,994]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:11,999]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,148]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:12,148]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,148]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,154]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,158]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:12,158]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,158]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,165]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,167]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:12,167]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,167]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,175]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,176]  INFO - CarbonUIServiceComponent Mgt Console URL  : https://localhost:9443/carbon/
[2024-02-13 15:34:12,177]  INFO - CarbonUIServiceComponent API Developer Portal Default Context : https://localhost:9443/devportal
[2024-02-13 15:34:12,177]  INFO - CarbonUIServiceComponent API Publisher Default Context : https://localhost:9443/publisher
[2024-02-13 15:34:12,181]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:12,181]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,181]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,187]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,189]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:12,189]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,189]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,195]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,202]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:12,202]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,202]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,209]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,212]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:12,212]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,212]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,218]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,225]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:12,225]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,225]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,231]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,233]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is set in APIHandlerServiceComponent
[2024-02-13 15:34:12,233]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,233]  INFO - JMSConnectionFactory JMS ConnectionFactory : Siddhi-JMS-Consumer initialized
[2024-02-13 15:34:12,239]  INFO - APIHandlerServiceComponent [TRACK] APIManagerConfigurationService is [UNSET] in APIHandlerServiceComponent
[2024-02-13 15:34:12,243] ERROR - Framework FrameworkEvent ERROR
java.lang.NullPointerException: null
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration_aroundBody12(ServiceReferenceHolder.java:133) ~[org.wso2.carbon.apimgt.gateway_9.29.22.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.internal.ServiceReferenceHolder.getAPIManagerConfiguration(ServiceReferenceHolder.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.22.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.InMemoryAPIDeployer.<init>(InMemoryAPIDeployer.java:83) ~[org.wso2.carbon.apimgt.gateway_9.29.22.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.cleanDeployment_aroundBody6(GatewayStartupListener.java:172) ~[org.wso2.carbon.apimgt.gateway_9.29.22.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.cleanDeployment(GatewayStartupListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.22.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.completingServerStartup_aroundBody0(GatewayStartupListener.java:129) ~[org.wso2.carbon.apimgt.gateway_9.29.22.SNAPSHOT.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.GatewayStartupListener.completingServerStartup(GatewayStartupListener.java:1) ~[org.wso2.carbon.apimgt.gateway_9.29.22.SNAPSHOT.jar:?]
```

**Comment by Lakith-Rambukkanage** [comment] 2024-02-14 10:06
The issue is caused by having multiple versions of the following jars. The lower versions are coming from the synapse which should also be bumped.

- okhttp_4.9.3.wso2v2.jar
- okhttp_4.11.0.wso2v1.jar
- okio_2.8.0.wso2v2.jar
- okio_3.5.0.wso2v1.jar
- opentelemetry-all_1.11.0.wso2v3.jar
- opentelemetry-all_1.11.0.wso2v4.jar

**Comment by Lakith-Rambukkanage** [comment] 2024-02-14 15:59
Encountered :

```
Cannot complete the install because one or more required items could not be found.
 Software being installed: WSO2 Carbon - Cache Mediator  Feature 4.7.193.SNAPSHOT (org.wso2.carbon.mediator.cache.server.feature.group 4.7.193.SNAPSHOT)
 Missing requirement: Zipkin Sender: OkHttp 3 2.16.3 (io.zipkin.reporter2.zipkin-sender-okhttp3 2.16.3) requires 'package okio [1.15.0,3.0.0)' but it could not be found
 Cannot satisfy dependency:
  From: WSO2 Carbon - Synapse Feature 4.0.0.wso2v84_SNAPSHOT (org.apache.synapse.wso2.feature.group 4.0.0.wso2v84_SNAPSHOT)
  To: io.zipkin.reporter2.zipkin-sender-okhttp3 [2.16.3]
 Cannot satisfy dependency:
  From: WSO2 Carbon - Cache Mediator  Feature 4.7.193.SNAPSHOT (org.wso2.carbon.mediator.cache.server.feature.group 4.7.193.SNAPSHOT)
  To: org.apache.synapse.wso2.feature.group [4.0.0.wso2v84_SNAPSHOT,4.1.0)

```

**Comment by lasanthaS** [comment] 2024-05-13 08:49
Closing this as this is fixed in the master

**Closed by lasanthaS** 2024-05-13 08:49 UTC
Labels: Type/Bug, Priority/Highest, Component/APIM, 4.3.0, 4.3.0-alpha, 4.3.0-M1
