### ISSUE TITLE
Choreo insights Overview page does not show the WebSocket throttled count under the Error Request Count

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/api-manager#1143] opened 2022-12-15 06:19 UTC
### Description

Refer to the below screenshot of the Overview page of Choreo Insights, taken after invoking a WebSocket API (which has been throttled 16 times) and a REST API (which has been throttled 2 times).

![image](https://user-images.githubusercontent.com/25246848/207785942-6ec42b29-2152-4ef8-bab5-42198701a1fe.png)

You can notice that the Error Request Count here is 2 which only considered REST API's throttled requests. It should be 18 actually because the WebSocket API also throttled out 16 times. So 2 + 16 = 18.

To further investigate, I clicked on the tile "Error Request Count" and it displayed the below page.

![image](https://user-images.githubusercontent.com/25246848/207786316-e3cde63c-4f43-4290-8bc7-f8e140e0b12d.png)

As you can see, the table contains all the throttled requests' details. According to that 16 were from WebSocket and 2 were from the REST API (PizzaShackAPI)

### Steps to Reproduce

1. Set up APIM with Choreo Insights as shown in [1].
2. Create, deploy and Publish a WebSocket API according to [2].
3. Subscribe to an Application that has 10PerMin tier and generate keys.
4. Invoke the WebSocket API more than 10 times within 1 minute so it will be throttled out. (Count the throttled times. Let's say it is X here)
5. Go to the Overview page of Choreo Insights and check the "Error Request Count". It will show 0 if you have not done any throttling for other types of APIs such as REST or GraphQL.

### Affected Component

Analytics

### Version

4.2.0-Pre-Alpha

### Related Issues
- https://github.com/wso2/api-manager/issues/1118

[1] https://apim.docs.wso2.com/en/4.2.0/api-analytics/getting-started-guide/#api-analytics-getting-started-guide
[2] https://apim.docs.wso2.com/en/4.2.0/design/create-api/create-streaming-api/create-a-websocket-streaming-api/

**Comment by madushadhanushka** [comment] 2023-03-01 08:00
This issue is reproducible and following I'm attaching the screenshots I got since the above description screenshots are having some problems.

Overview page:
<img width="1487" alt="Screenshot 2023-03-01 at 13 25 03" src="https://user-images.githubusercontent.com/7068605/222078346-3f3823e9-d06e-4c20-a55a-dbcb4c9b21b4.png">

Error page:
<img width="1224" alt="Screenshot 2023-03-01 at 13 27 24" src="https://user-images.githubusercontent.com/7068605/222078491-91bc8d90-7931-40d5-9dc2-649a6be28256.png">

The overview page contains `Error Request Count` as 10. For the error page, there are 10 errors for PizzaShackAPI and 5 for Chat API. Seems overview page only aggregate errors for REST API.

**Comment by madushadhanushka** [comment] 2023-03-02 05:18
This ticket is closing hence this should fix from the Choreo backend. Please refer https://github.com/wso2-enterprise/choreo/issues/19113

**Closed** 2023-03-02 06:06 UTC
Labels: Type/Bug, Priority/Normal, Component/APIM, Component/Analytics, 4.x.x, 4.2.0-RC
