### ISSUE TITLE
[4.0.0][MI]DSS Calls which has Stored Procedure are failing after enabling Correlation Logs [public]

### ISSUE THREAD

**Issue by dinithnirman** [wso2/api-manager#1998] opened 2023-07-11 09:38 UTC
### Description

Currently, we are using Micro Integrator 4.0.0. When we enable the correlation logs, data service calls that have stored procedures are failing with the below error.

```
[2023-06-27 11:53:07,066] ERROR \{DBInOutMessageReceiver\} - Error in in-out message receiver DS Code: DATABASE_ERROR\
Nested Exception:-\
javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'SQLQuery.processStoredProcQuery': DS Fault Message: Error in 'createProcessedPreparedStatement'\
DS Code: UNKNOWN_ERROR\
Nested Exception:-\
java.sql.SQLException: Statement closed.\
\
DS Code: DATABASE_ERROR\
Source Data Service:-\
Name: tips-fund-transfer-v1-wso2-dataservice\
Location: /home/wso2carbon/wso2mi-4.0.0/tmp/carbonapps/-1234/1687855904399tips-fund-transfer-cap.car/tips-fund-transfer-v1-wso2-dataservice_1.0.35/tips-fund-transfer-v1-wso2-dataservice-1.0.35.dbs\
Description: \
Default Namespace: http://ws.wso2.org/dataservice\
Current Request Name: _puttips-transfer-requests-success-callback-status-update\
Current Params: \{PAYER_REF=003-188fc0e59ed898ae, SWITCH_REF=56ee7843-8b92-4ebd-8826-92f093b3266e, INTERNAL_PROCESSING_STATUS=RESPONSE_RECIEVED, COMPLETED_TIMESTAMP=27-JUN-23 11:53:06, TIPS_STATUS=COMMITTED, PAYEE_REF=511-BW230627.1153.A04029\}\
Nested Exception:-\
DS Fault Message: Error in 'createProcessedPreparedStatement'\
DS Code: UNKNOWN_ERROR\
Nested Exception:-\
java.sql.SQLException: Statement closed.\
\
\
\
	at org.wso2.micro.integrator.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:74)\
	at org.wso2.micro.integrator.dataservices.core.dispatch.DataServiceRequest.dispatch(DataServiceRequest.java:358)\
	at org.wso2.micro.integrator.dataservices.core.DataServiceProcessor.dispatch(DataServiceProcessor.java:40)\
	at org.wso2.micro.integrator.dataservices.core.DBInOutMessageReceiver.invokeBusinessLogic(DBInOutMessageReceiver.java:81)\
	at org.apache.axis2.receivers.AbstractInOutSyncMessageReceiver.invokeBusinessLogic(AbstractInOutSyncMessageReceiver.java:42)\
	at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)\
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)\
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:375)\
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:434)\
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182)\
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)\
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\
	at java.base/java.lang.Thread.run(Thread.java:829)\
Caused by: javax.xml.stream.XMLStreamException: DS Fault Message: Error in 'SQLQuery.processStoredProcQuery': DS Fault Message: Error in 'createProcessedPreparedStatement'\
DS Code: UNKNOWN_ERROR\
Nested Exception:-\
java.sql.SQLException: Statement closed.\
\
DS Code: DATABASE_ERROR\
Source Data Service:-\
Name: tips-fund-transfer-v1-wso2-dataservice\
Location: /home/wso2carbon/wso2mi-4.0.0/tmp/carbonapps/-1234/1687855904399tips-fund-transfer-cap.car/tips-fund-transfer-v1-wso2-dataservice_1.0.35/tips-fund-transfer-v1-wso2-dataservice-1.0.35.dbs\
Description: \
Default Namespace: http://ws.wso2.org/dataservice\
Current Request Name: _puttips-transfer-requests-success-callback-status-update\
Current Params: \{PAYER_REF=003-188fc0e59ed898ae, SWITCH_REF=56ee7843-8b92-4ebd-8826-92f093b3266e, INTERNAL_PROCESSING_STATUS=RESPONSE_RECIEVED, COMPLETED_TIMESTAMP=27-JUN-23 11:53:06, TIPS_STATUS=COMMITTED, PAYEE_REF=511-BW230627.1153.A04029\}\
Nested Exception:-\
DS Fault Message: Error in 'createProcessedPreparedStatement'\
DS Code: UNKNOWN_ERROR\
Nested Exception:-\
java.sql.SQLException: Statement closed.\
\
\
	at org.wso2.micro.integrator.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:100)\
	at org.wso2.micro.integrator.dataservices.core.dispatch.SingleDataServiceRequest.processRequest(SingleDataServiceRequest.java:72)\
	... 13 more\
Caused by: DS Fault Message: Error in 'SQLQuery.processStoredProcQuery': DS Fault Message: Error in 'createProcessedPreparedStatement'\
DS Code: UNKNOWN_ERROR\
Nested Exception:-\
java.sql.SQLException: Statement closed.
```
Could you please check the issue and update us with a solution.

### Steps to Reproduce

N/A

### Affected Component

Analytics

### Version

4.0.0

**Comment by GihanAyesh** [comment] 2023-08-23 06:43
The issue is resolved with PR: https://github.com/wso2/micro-integrator/pull/2913

**Closed by GihanAyesh** 2023-08-23 06:43 UTC
Labels: Type/Bug, Missing/Component
