### ISSUE TITLE
Value too long for column "DETAILS VARCHAR(5000)

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/api-manager#206] opened 2022-06-20 08:40 UTC
### Description

When migrating existing WSO2 EI/ESB environments to the WSO2 MI 4.x.x environments, it is possible to have artefacts that exceed the expected "DETAILS" column. The user in the observed environment is manually deploying synapse artifacts (not with the help of the integration studio.

### Steps to Reproduce

* Please apply the artifact attached in <censored> to `<MI_HOME>/repository/deployment/server/synapse-configs/default/api` and re-start the MI dashboard server.

### Affected Component

MIDashboard

### Version

4.0.1.13

### Environment Details (with versions)

**Product:** WSO2 MI 4.0.1.13
**Update level:** 4.0.1.13
**OS:** any
**Java version:** any

### Relevant Log Output

```shell
at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.dml.Insert.update(Insert.java:151)
	at org.h2.command.dml.Insert.insertRows(Insert.java:187)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:378)
	at org.h2.value.TypeInfo.cast(TypeInfo.java:520)
	at org.h2.value.TypeInfo.getValueTooLongException(TypeInfo.java:535)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
INSERT INTO APIS VALUES (?,?,?,?); [22001-200]
Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column "DETAILS VARCHAR(5000)": "'{""tracing"":""disabled"",""stats"":""disabled"",""port"":-1,""name"":""SecurityDataService-V4"",""context"":""/security-data-service-v4"",""resou... (6947)"; SQL statement:
	at java.base/java.lang.Thread.run(Thread.java:834)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at org.wso2.ei.dashboard.micro.integrator.MiArtifactsManager.lambda$runFetchAllExecutorService$0(MiArtifactsManager.java:103)
	at org.wso2.ei.dashboard.micro.integrator.MiArtifactsManager.processArtifacts(MiArtifactsManager.java:158)
	at org.wso2.ei.dashboard.micro.integrator.MiArtifactsManager.insertArtifact(MiArtifactsManager.java:181)
	at org.wso2.ei.dashboard.core.db.manager.JDBCDatabaseManager.insertArtifact(JDBCDatabaseManager.java:119)
Exception in thread "pool-4-thread-6" org.wso2.ei.dashboard.core.exception.DashboardServerException: Error occurred while inserting SecurityDataService-V4 information.
[2022-06-14 07:44:10,373]  INFO {MiArtifactsManager} - Fetching artifacts from node 50280a55-ec58-40c8-a6df-021032614073 in group mi_dev
[2022-06-14 07:44:10,373]  INFO {HeartBeatDelegate} - Management URL is: https://<censored>/management/
[2022-06-14 07:44:10,372]  INFO {HeartBeatDelegate} - Successfully registered the node: 50280a55-ec58-40c8-a6df-021032614073 in group: mi_dev
[2022-06-14 07:44:08,801]  INFO {HeartBeatDelegate} - Management URL is: https://<censored>/management/
[2022-06-14 07:44:08,800]  INFO {HeartBeatDelegate} - Registering the new node 50280a55-ec58-40c8-a6df-021032614073 in group : mi_dev
	... 6 more
	at org.wso2.ei.dashboard.core.db.manager.JDBCDatabaseManager.insertArtifact(JDBCDatabaseManager.java:117)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191)
	at org.h2.command.Command.executeUpdate(Command.java:251)
	at org.h2.command.CommandContainer.update(CommandContainer.java:198)
	at org.h2.command.dml.Insert.update(Insert.java:151)
	at org.h2.command.dml.Insert.insertRows(Insert.java:187)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:378)
	at org.h2.value.TypeInfo.cast(TypeInfo.java:520)
	at org.h2.value.TypeInfo.getValueTooLongException(TypeInfo.java:535)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
INSERT INTO APIS VALUES (?,?,?,?); [22001-200]
Caused by: org.h2.jdbc.JdbcSQLDataException: Value too long for column "DETAILS VARCHAR(5000)": "'{""tracing"":""disabled"",""stats"":""disabled"",""port"":-1,""name"":""SecurityDataService-V4"",""context"":""/security-data-service-v4"",""resou... (6947)"; SQL statement:
```
```


### Related Issues

N/A

### Suggested Labels

patch, p2, incident

**Comment by sajinieKavindya** [comment] 2022-06-21 10:53
Duplicate of https://github.com/wso2/product-mi-tooling/issues/218

**Closed** 2022-08-30 10:55 UTC
Labels: Type/Bug, Priority/Normal, Component/MIDashboard
