### ISSUE TITLE
Error in importing com.jayway.jsonpath from U2 level EI-6.6.0.149

### ISSUE THREAD

**Issue by karunarathneeshani** [wso2/api-manager#2325] opened 2023-12-14 07:46 UTC
### Description

The following issue can be observed when placing the org.wso2.carbon.framework.extension.json_20090211_1.0.0.jar  file to the <EI_HOME>/dropins directory from U2 level EI-6.6.0.149 onwards.

[2023-12-13 12:48:14,268] ERROR {org.wso2.carbon.application.deployer.internal.ApplicationManager} - Error occurred while deploying Carbon Application org.apache.axis2.deployment.DeploymentException: com/jayway/jsonpath/PathNotFoundException

### Steps to Reproduce

1] Update the WSO2 EI-6.6.0 server to the U2 level 148.
2] Add the attached lib folder at the link[2] to the pack and, start the server.
3] Stop the server and, add the dropping jars at the link[2] to the dropins folder.
4] Start the server and, deploy the attached car file.
5] Car app will deploy without any issue.
6] Update the server to the 149.
7] Start the server.
8] The error will be observed while deploying the car file.
9] Remove the "org.wso2.carbon.framework.extension.json_20090211_1.0.0.jar" from the dropping folder and, restart the server.
10] The issue will resolved.
11] Enable the OSGI console and, check the import and, export dependancies for synapse-core_2.1.7.wso2v143_104 (for U2 148) and synapse-core_2.1.7.wso2v143_108 (for U2 149).
12] The com.jayway.jsonpath is not importing to the problematic U2 149.

### Affected Component

APIM

### Version

6.6.0

**Comment by GDLMadushanka** [comment] 2024-01-02 02:30
Closing hence the issue is introduced from the manually added jar org.wso2.carbon.framework.extension.json_20090211_1.0.0.jar

**Closed by GDLMadushanka** 2024-01-02 02:30 UTC
Labels: Type/Bug, Missing/Component
