### ISSUE TITLE
Unable to Preserve Authorization Header

### ISSUE THREAD

**Issue by MickAntonio** [wso2/api-manager#788] opened 2022-10-10 10:18 UTC
### Description

I tried to preserve my Authorization by changing API Manager global configuration to:

`<RemoveOAuthHeadersFromOutMessage>false</RemoveOAuthHeadersFromOutMessage>`

and TOML configuration to:

```
[apim.oauth_config]
enable_outbound_auth_header = true
```

but it still removing the Authorization header, i have tested it on version 4.0 and 4.1 of api-manager.

### Steps to Reproduce

Alter API Manager global configuration to:

`<RemoveOAuthHeadersFromOutMessage>false</RemoveOAuthHeadersFromOutMessage>`

and TOML configuration to:

```
[apim.oauth_config]
enable_outbound_auth_header = true
```

### Affected Component

APIM

### Version

4.0 and 4.1

### Environment Details (with versions)

Windows 10

**Comment by piyumaldk** [comment] 2023-02-28 12:02
### Work Log [2023-02-28]

- Rebased and built the latest master and got the latest APIM pack.
- Enabled wire log to observe HTTPS-Listener I/O dispatchers and HTTPS-Sender I/O dispatchers.
- Tried with and without enabling (above mentioned two steps) and gp through the wire log.
    - Wasn’t able to reproduce the issue.
    - `[2023-02-28 17:22:06,488] DEBUG - wire HTTPS-Sender I/O dispatcher-1 << "Authorization: Bearer <token>[\r][\n]"`. This wire log was printed and hence it’s sending the Authorization Bearer to backend from the gateway. 
- Debugged and found some related information on this.
    - There is a method called AuthenticationResponse in carbon-apimgt/components/apimgt/org.wso2.carbon.apimgt.gateway/src/main/java/org/wso2/carbon/apimgt/gateway/handlers/security/oauth/OAuthAuthenticator.java.
    - In this file, 
```
if (removeOAuthHeadersFromOutMessage) {
   //Remove authorization headers sent for authentication at the gateway and pass others to the backend
   if (StringUtils.isNotBlank(remainingAuthHeader.get())) {
       if (log.isDebugEnabled()) {
           log.debug("Removing OAuth key from Authorization header");
       }
       headers.put(getSecurityHeader(), remainingAuthHeader);
   } else {
       if (log.isDebugEnabled()) {
           log.debug("Removing Authorization header from headers");
       }
       headers.remove(getSecurityHeader());
   }
}
```
- This removeOAuthHeadersFromOutMessage is coming from isRemoveOAuthHeadersFromOutMessage in OAuthAuthenticator. This is taken from RemoveOAuthHeadersFromOutMessage value of API Manager configurations. This is stored in /repository/conf/api-manager.xml. Make sure to change the correct file since there may be duplicates in the backup directory. 

- Closing this issue since unable to reproduce it using the above mentioned steps.

**Closed by piyumaldk** 2023-02-28 12:02 UTC
Labels: Type/Bug, Priority/High, Affected/APIM-4.0.0, Missing/Component, Affected/MI-4.1.0, 4.2.0-RC
