### ISSUE TITLE
Origin header validation in WS transport - APIM 3.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#612] opened 2022-08-11 00:32 UTC
### Problem

Currently, if we configured the **Origin** header validation for the WS transport, the **Origin** header will validate even if the header is not in the request.

### Solution

Need to validate the **Origin** header value in the web socket transport if the **Origin** header is in the request

### Affected Component

APIM

### Version

3.2.0

**Comment by SupunTharakaSandaruwan** [comment] 2022-08-16 04:34
Hi Team,

Customer has modified the requirement as follows.

`Also we need some way to update origin header values at runtime for websocket apis. Because to add origin header value we can't do a deployment in production environment. It will be very costly effort we need to spend in higher environment.
In REST we have cors_request_handler.xml sequence file where we can add allow origin header at runtime. This is not require any deployment. Similar kind of approach we are expecting for websocket api as well.
we mentioned this information in the last meeting as well. Please consider all the scenarios discuss with your product team and let us know.
Websocket origin header addition should have some kind of leverage like REST and can be add at runtime. This is what our expectation.`

Please consider these requirements as well when the improvement is given.

**Comment by PasanT9** [comment] 2022-11-10 06:12
Following PRs cover origin header validation per API.

https://github.com/wso2/apim-apps/pull/378
https://github.com/wso2/carbon-apimgt/pull/11622

**Comment by PasanT9** [comment] 2022-12-01 12:02
Please note that this improvement can be managed using API Handlers in APIM 4.x version. Until this implementation is confirmed with a POC we will need to hold the issue.

**Comment by YasasRangika** [comment] 2024-01-08 07:03
closing this issue since the master fix: https://github.com/wso2/carbon-apimgt/pull/11908 has already been merged into the master branch.
Refer: https://github.com/wso2/api-manager/issues/1484 as per the comment [1].

[1] https://github.com/wso2/api-manager/issues/612#issuecomment-1333662010

**Closed by YasasRangika** 2024-01-08 07:03 UTC
Labels: Type/Improvement, Priority/Normal, Affected/APIM-3.2.0, U2/WUM, onHold, 4.3.0, 4.3.0-M1
