### ISSUE TITLE
Cannot invoke APIs when the tokens generated by AzureKD key manager in Distributed setup

### ISSUE THREAD

**Issue by shnrndk** [wso2/api-manager#2666] opened 2024-03-18 05:04 UTC
### Description

After enabling the azurekd key manager, the tokens can generate without any issues by clicking on the `Generate Keys` button.
But users can't invoke the apis using the keys generated by AzureAD key manager. When invoking it shows this error message.
```
{"code":"900900","message":"Unclassified Authentication Failure","description":"Error while accessing backend services for API key validation"}%     
```

### Steps to Reproduce

1.) Setup the Azure AD keymanager
2.) Generate Keys
3.) Invoke the APIs

### Affected Component

APIM

### Version

4.3.0 Alpha

**Comment by chamilaadhi** [comment] 2024-03-20 09:22
Seems like there is an issue when configuring the keymanager. 'Issuer' and claim for the client id has been changed in Azure side. Issuer in the token is not equal to the issuer received from the well-know URL. Also client id is now received from the `appid` claim in the JWT (previously this was retrieved from `azp` claim)

After changing the issuer ('Issuer' : 'https://sts.windows.net/<xxxxxxxxxx>/' ) and the 'Claim URIs'  to `appid` , this worked

**Comment by tharikaGitHub** [comment] 2024-03-21 15:07
Closing as the issue is addressed.

**Closed by tharikaGitHub** 2024-03-21 15:07 UTC
Labels: Type/Bug, Severity/Critical, Priority/High, Component/APIM, 4.3.0-alpha, Affected/APIM-4.3.0, BugFixing

**Comment by lahirugmg** [comment] 2024-09-07 09:08
Team, 

Documentation is not updated related to this change. It would be great to have this in the doc correctl.

[1] https://apim.docs.wso2.com/en/latest/administer/key-managers/configure-azure-ad-key-manager/
