### ISSUE TITLE
TenantDomain param name issue

### ISSUE THREAD

**Issue by shavinsenadheera** [wso2/api-manager#2344] opened 2023-12-26 08:26 UTC
### Description

When clicking on the "Proceed to Self Register" button it redirects to a page resulting in a 500 response. 

![image](https://github.com/wso2/api-manager/assets/42552426/e9d2687b-7512-43b0-8b7c-1a87fbe8fb3d)

![image](https://github.com/wso2/api-manager/assets/42552426/810e356a-7a1b-44bd-bb38-6845f8d919b7)

And, were able to see the following error logs on the APIM server side.

[errors.log](https://github.com/wso2/api-manager/files/13769965/errors.log)

When we analyzed the codes and redirect URLs thoroughly we were able to see the following behaviour.

Rename the "TenantDomain" parameter in the URL to "tenantDomain" as follows and, the flow is working as expected.

```
https://localhost:9443/accountrecoveryendpoint/register.do?TenantDomain
```
```
https://localhost:9443/accountrecoveryendpoint/register.do?tenantDomain
```
### Steps to Reproduce

1. Set the JiT Provisioning as “Prompt for username, password and consent” to persist the password as well in the APIM user store side.

![Screenshot from 2023-12-06 18-38-11](https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/31a7dc78-4574-4058-a43d-e3bf459dab43)

2. Click the SIGN-IN button on the developer portal.
3. Add the username and password of the Microsoft account.

![Screenshot from 2023-12-06 18-45-42](https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/6b0adbe8-cb63-45ca-a6a8-b964f855be5b)

4. Then, redirects to the wso2 page with the UID which is sent from the Azure Side.

![Screenshot from 2023-12-06 20-09-54](https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/61185c7b-e84c-452b-a218-d141a1aa8a63)

5. If we click on the “Proceed to Self Register”, it redirects to the following page and returns 500 response page as follows.

![Screenshot from 2023-12-06 20-10-42](https://github.com/wso2-enterprise/wso2-apim-internal/assets/42552426/85bb0e9c-ec17-440b-92a1-d322b2d80826)

### Affected Component

APIM

### Version

4.0.0

**Comment by tharikaGitHub** [comment] 2024-03-31 11:27
Closing as the issue is already fixed in APIM 4.3.0-Alpha

**Closed by tharikaGitHub** 2024-03-31 11:27 UTC
Labels: Type/Bug, Component/APIM, Affected/APIM-4.0.0, 4.3.0
