### ISSUE TITLE
Production/Sandbox Application Registration workflows not working

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#2550] opened 2024-03-01 11:24 UTC
### Description

Production/Sandbox Application Registration workflows not working

### Steps to Reproduce

Follow https://apim.docs.wso2.com/en/latest/consume/manage-application/advanced-topics/adding-an-application-key-generation-workflow/

Will get redirected to an empty page in both Production and Sandbox scenarios in 5th step.

The following is the error in Browser console.

<img width="813" alt="Screen Shot 2024-03-01 at 5 09 58 PM" src="https://github.com/wso2/api-manager/assets/8557410/0fb1c830-15e5-472b-b50a-e21913316c42">

### Affected Component

APIM

### Version

4.3.0-M2 (Post M2 pack with React Bump)

### Environment Details (with versions)

Distributed setup in cloud

**Comment by tharikaGitHub** [comment] 2024-03-03 03:58
Closing as the issue is fixed.

**Closed by tharikaGitHub** 2024-03-03 03:58 UTC
Labels: Type/Bug, Severity/Major, Component/APIM, React-UI, 4.3.0, 4.3.0-alpha
