### ISSUE TITLE
WSO2 API Manager 4.1: IdentityUtil Class Definition Not Found Error in startup

### ISSUE THREAD

**Issue by mjfcampos** [wso2/api-manager#785] opened 2022-10-09 18:18 UTC
### Description

The following issues occur while the WSO2 apim starts up:

TID: [-1234] [] [2022-10-09 14:52:58,279] ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/accountrecoveryendpoint]} - Exception sending context initialized event to listener instance of class [org.wso2.carbon.identity.mgt.endpoint.util.listener.IdentityManagementEndpointContextListener] java.lang.NoClassDefFoundError: org/wso2/carbon/identity/core/util/**IdentityUtil**

TID: [-1234] [] [2022-10-09 14:52:58,367] ERROR {org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer} - Error while deploying webapp: StandardContext[accountrecoveryendpoint].File[/opt/wso2am/repository/deployment/server/webapps/**accountrecoveryendpoint**] org.wso2.carbon.tomcat.CarbonTomcatException: Webapp failed to deploy

Because of that, the access to /admin, /publisher, and /devportal is not working.

I already tried the recommended workaround posted here https://stackoverflow.com/questions/72158227/identityutil-class-definition-not-found-error-in-wso2-api-manager-4-1-startup, but it does not work.

It seems that the problem is happening only on INTEL processors. I installed the WSO2 APIM on an ARM64 Ubuntu Server 20.04.5 and couldn't reproduce the problem.

Regards,
Marcelo

### Steps to Reproduce

Virtual machine with Ubuntu Server 20.04.5 LTS
Downgrade to kernel  5.4.0-84-generic
Download wso2am-4.1.0.zip
uncompress wso2am-4.1.0.zip
cd wso2am-4.1.0/bin
./api-manager.sh

### Affected Component

APIM

### Version

4.1.0

### Environment Details (with versions)

SO: Ubuntu 20.04.5 LTS

Kernel: 5.4.0-84-generic x86_64

JDK: 
java version "11.0.16.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.16.1+1-LTS-1)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.16.1+1-LTS-1, mixed mode)

ANT: Apache Ant(TM) version 1.10.7 compiled on October 24 2019

### Relevant Log Output

```shell
2022-10-09T14:52:58,279 [-] [Framework Event Dispatcher: Equinox Container: a4353321-2bc9-426d-9e92-9b8a9115d349] ERROR [/accountrecoveryendpoint] Exception sending context initialized event to listener instance of class [org.wso2.carbon.identity.mgt.endpoint.util.listener.IdentityManagementEndpointContextListener]
java.lang.NoClassDefFoundError: org/wso2/carbon/identity/core/util/IdentityUtil
        at org.wso2.carbon.identity.mgt.endpoint.util.IdentityManagementServiceUtil.init(IdentityManagementServiceUtil.java:130) ~[org.wso2.carbon.identity.mgt.endpoint.util_5.18.248.jar:?]
        at org.wso2.carbon.identity.mgt.endpoint.util.listener.IdentityManagementEndpointContextListener.contextInitialized(IdentityManagementEndpointContextListener.java:34) ~[org.wso2.carbon.identity.mgt.endpoint.util_5.18.248.jar:?]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4768) ~[tomcat_9.0.58.wso2v1.jar:?]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230) ~[tomcat_9.0.58.wso2v1.jar:?]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat_9.0.58.wso2v1.jar:?]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726) ~[tomcat_9.0.58.wso2v1.jar:?]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698) ~[tomcat_9.0.58.wso2v1.jar:?]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696) ~[tomcat_9.0.58.wso2v1.jar:?]
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:303) ~[?:?]
        at org.wso2.carbon.tomcat.internal.CarbonTomcat.addWebApp(CarbonTomcat.java:209) ~[?:?]
        at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleWebappDeployment(TomcatGenericWebappsDeployer.java:255) ~[org.wso2.carbon.webapp.mgt_4.11.3.jar:?]
        at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleExplodedWebappDeployment(TomcatGenericWebappsDeployer.java:243) ~[org.wso2.carbon.webapp.mgt_4.11.3.jar:?]
        at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.handleHotDeployment(TomcatGenericWebappsDeployer.java:173) ~[org.wso2.carbon.webapp.mgt_4.11.3.jar:?]
        at org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer.deploy(TomcatGenericWebappsDeployer.java:140) ~[org.wso2.carbon.webapp.mgt_4.11.3.jar:?]
        at org.wso2.carbon.webapp.mgt.AbstractWebappDeployer.deployThisWebApp(AbstractWebappDeployer.java:224) ~[org.wso2.carbon.webapp.mgt_4.11.3.jar:?]
        at org.wso2.carbon.webapp.mgt.AbstractWebappDeployer.deploy(AbstractWebappDeployer.java:114) ~[org.wso2.carbon.webapp.mgt_4.11.3.jar:?]
        at org.wso2.carbon.webapp.deployer.WebappDeployer.deploy(WebappDeployer.java:42) ~[org.wso2.carbon.webapp.deployer_4.11.3.jar:?]
        at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136) ~[axis2_1.6.1.wso2v80.jar:?]
        at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807) ~[axis2_1.6.1.wso2v80.jar:?]
        at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:153) ~[axis2_1.6.1.wso2v80.jar:?]
        at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377) ~[axis2_1.6.1.wso2v80.jar:?]
        at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254) ~[axis2_1.6.1.wso2v80.jar:?]
        at org.apache.synapse.Axis2SynapseController.deployMediatorExtensions(Axis2SynapseController.java:785) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
        at org.apache.synapse.Axis2SynapseController.createSynapseEnvironment(Axis2SynapseController.java:403) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
        at org.apache.synapse.ServerManager.start(ServerManager.java:187) ~[synapse-core_2.1.7.wso2v271.jar:2.1.7-wso2v271]
        at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.initESB(ServiceBusInitializer.java:371) ~[org.wso2.carbon.mediation.initializer_4.7.131.jar:?]
        at org.wso2.carbon.mediation.initializer.ServiceBusInitializer.activate(ServiceBusInitializer.java:170) ~[org.wso2.carbon.mediation.initializer_4.7.131.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.wso2.carbon.inbound.endpoint.persistence.service.InboundEndpointPersistenceServiceDSComponent.activate(InboundEndpointPersistenceServiceDSComponent.java:50) ~[org.wso2.carbon.inbound.endpoint.persistence_4.7.131.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) ~[org.eclipse.equinox.ds_1.4.400.v20160226-2036.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:113) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:985) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:866) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:525) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:544) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:529) ~[org.wso2.carbon.core_4.6.3.jar:?]
        at org.wso2.carbon.core.init.CarbonServerManager.removePendingItem(CarbonServerManager.java:305) ~[org.wso2.carbon.core_4.6.3.jar:?]
        at org.wso2.carbon.core.init.PreAxis2ConfigItemListener.bundleChanged(PreAxis2ConfigItemListener.java:118) ~[org.wso2.carbon.core_4.6.3.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.identity.core.util.IdentityUtil
        at org.wso2.carbon.webapp.mgt.loader.CarbonWebappClassLoader.loadClass(CarbonWebappClassLoader.java:195) ~[org.wso2.carbon.webapp.mgt_4.11.3.jar:?]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1215) ~[tomcat_9.0.58.wso2v1.jar:?]
        ... 76 more
```

**Comment by malinthaprasan** [comment] 2023-02-27 10:21
We got the same issue in Choreo build pipelines
Ubuntu 22.04.2

**Comment by dulanjalidilmi** [comment] 2023-03-03 11:01
I have created a patch ticket for 4.1.0, since this issue is not reproducing in master.

**Comment by YasasRangika** [comment] 2024-01-10 06:04
Closing as per the https://github.com/wso2/api-manager/issues/785#issuecomment-1453355260

**Closed by YasasRangika** 2024-01-10 06:04 UTC
Labels: Type/Bug, Priority/High, Affected/APIM-4.1.0
