### ISSUE TITLE
UI Bugs in the Publisher Portal - APIM 4.1.0

### ISSUE THREAD

**Issue by VinulaUthsara** [wso2/api-manager#1055] opened 2022-11-30 07:16 UTC
### Description

There are several UI bugs that are observed in the Publisher Portal of APIM 4.1.0. These are as follows:

1. Total: number of APIs does not change if an API is deleted from the Publisher:

![Screenshot from 2022-11-25 11-56-15](https://user-images.githubusercontent.com/39290953/204730648-13718bfc-f57a-4159-bdcc-23386643354f.png)

2. If an invalid file format is provided when importing an API, errors are shown along with the “Show Errors” information text. Even after the errors appearing above are closed or a valid API file is re-uploaded the “Show Errors” text is still present:

![Screenshot from 2022-11-25 12-40-05](https://user-images.githubusercontent.com/39290953/204730702-a391131c-51f9-4b56-897f-092d48f0639b.png)

3. When trying out an API with a “/*” resource in the Developer portal it is working correctly as follows:

![Screenshot from 2022-11-29 12-36-51](https://user-images.githubusercontent.com/39290953/204730757-dc7a5389-1543-4449-93f2-7568945482f0.png)

![Screenshot from 2022-11-29 12-36-34](https://user-images.githubusercontent.com/39290953/204730780-8bd8b322-5126-49ee-8044-52c6d2cd4fec.png)

 
However, when trying the same via the Publisher portal the /* is not getting parsed properly and is also visible in the request details as observed via the endpoint request details.

![Screenshot from 2022-11-29 12-39-43](https://user-images.githubusercontent.com/39290953/204730798-e524d0fa-3b32-4982-9acd-90b511d92561.png)

![Screenshot from 2022-11-29 12-39-10](https://user-images.githubusercontent.com/39290953/204730814-d8891a07-394b-4bf8-a946-271440c85d67.png)

 
 
This causes errors such as 404 errors when testing the resource from the Publisher portal but receive 200 response and API call is successful when trying out via the Developer portal.

### Steps to Reproduce

1. Create multiple APIs and delete an API. The API count will show a wrong number than the existing APIs; typically 1 more than the correct number

2. From Publisher go to Create API -> Start from Scratch -> Upload API file. Upload an invalid file such as a PDF: this will show errors. Re-upload a valid API file the 'Show Errors' button will still persist.

3. Resources with "/*" are passed properly in the Developer Portal, but Publisher portal is showing /* in the request url.

### Affected Component

APIM

### Version

4.1.0

**Comment by Lakith-Rambukkanage** [comment] 2022-12-15 11:24
## Update on Incorrect total API count after delete issue

The issue is caused by an indexing delay in the registry and is considered an expected behaviour. ATM this issue will not be fixed as it does not disrupt the product functionalities, and as the correct count is displayed upon refreshing/revisiting the page.

**Comment by YasasRangika** [comment] 2024-01-08 10:43
Closing as the public fix: https://github.com/wso2/apim-apps/pull/410 has been merged to the master branch.

**Closed by YasasRangika** 2024-01-08 10:43 UTC
Labels: Type/Bug, Priority/Normal, Affected/APIM-4.1.0, 4.3.0, 4.3.0-M1
