### ISSUE TITLE
Error while deploying Siddhi APPs in SI 4.1.0

### ISSUE THREAD

**Issue by jichinthaka** [wso2/api-manager#1384] opened 2023-02-06 10:54 UTC
### Description

Hi Team, 
Receive the following errors while deploying Siddhi APPs.

```
Unresolved requirement: Import-Package: org.apache.log4j; version="[1.2.0,2.0.0)"
org.osgi.framework.BundleException: Could not resolve module: siddhi-execution-string [169]
 
org.wso2.carbon.databridge.core.exception.EventConversionException: No StreamDefinition for streamId org.wso2.apimgt.statistics.request:3.2.0 present in cache 
ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} - Dropping wrongly formatted event sent org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.apimgt.statistics.request:3.2.0 of event bundle with events 1
ERROR {org.wso2.carbon.databridge.core.internal.queue.QueueWorker} - Dropping wrongly formatted event sent org.wso2.carbon.databridge.core.exception.EventConversionException: Error when converting org.wso2.apimgt.statistics.request:3.2.0 of event bundle with events 1
Caused by: io.siddhi.core.exception.SiddhiAppCreationException: Error on 'XXXXXXXX' @ Line: 54. Position: 26, near '@source(type = 'wso2event', wso2.stream.id = 'org.wso2.apimgt.statistics.fault:3.2.0',

ERROR {org.wso2.carbon.streaming.integrator.core.internal.StreamProcessorDeployer} - io.siddhi.core.exception.SiddhiAppCreationException: Error on 'XXXXXXXXX' @ Line: 54. Position: 26, near '@source(type = 'wso2event', wso2.stream.id = 'org.wso2.apimgt.statistics.fault:3.2.0',
```

### Steps to Reproduce

N/A

### Affected Component

SI

### Version

4.1.0

**Comment by GihanAyesh** [comment] 2023-03-31 08:42
The issue is resolved by updating the following jar files,

- siddhi-io-wso2event - 5.0.1 --> 5.0.2
- siddhi-map-wso2event - 5.0.2 --> 5.0.3

Hence closing the issue.

**Closed by GihanAyesh** 2023-03-31 08:42 UTC
Labels: Type/Bug, Affected/SI-4.1.0
