### ISSUE TITLE
UI Deployment Tooltip Issue

### ISSUE THREAD

**Issue by dinuka10** [wso2/api-manager#2105] opened 2023-08-17 18:34 UTC
### Description

When there are multiple virtual hosts [1], attempting to deploy a new revision and selecting the VHost causes a tooltip to appear over the endpoints. This tooltip covers the dropdown menu, as shown in the attached screenshot. ( Screenshot from 2023-08-17 10-43-56.png)
![Screenshot from 2023-08-17 10-43-56](https://github.com/wso2/api-manager/assets/44248646/53052358-60bd-4ad8-aecf-37024aab2c99)

### Steps to Reproduce

1.) Follow the steps outlined in the documentation [2] to define the host names.

2.) Give lengthy URLs for both the http_endpoint and https_endpoint, then restart the server

3.) Deploy the "pizzashack" API and try to deploy a new revision

4.) When navigating to the API gateways and selecting a different VHost, hovering the mouse cursor over that location will reveal that the dropdown list of VHosts covers the endpoint URLs for the selected VHost, as depicted in the attached screenshot.

![Screenshot from 2023-08-17 10-43-56](https://github.com/wso2/api-manager/assets/44248646/72048461-24bb-4f8f-a381-7c96b05c6975)

[1] https://apim.docs.wso2.com/en/4.1.0/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames/#using-an-existing-gateway-environment-to-expose-apis-via-custom-hostnames
[2] https://apim.docs.wso2.com/en/4.1.0/deploy-and-publish/deploy-on-gateway/deploy-api/exposing-apis-via-custom-hostnames/#step-1-define-the-custom-hostnames

### Affected Component

APIM

### Version

wso2am-4.1.0

**Comment by tharikaGitHub** [comment] 2024-03-28 15:31
Closing as the issue is fixed in the public branch with PR https://github.com/wso2/apim-apps/pull/643.

**Closed by tharikaGitHub** 2024-03-28 15:31 UTC
Labels: Type/Bug, Component/APIM, U2/WUM, 4.3.0
