### ISSUE TITLE
Issuer is not set as JWT for service providers when the config is enabled 

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2781] opened 2024-04-01 12:01 UTC
### Description

Issuer is not set as JWT for service providers when the config is enabled.  If the token persistence configs are enabled with this feature, users cannot login to portals if a tenant user tries to login to the devportal of super tenant.

<img width="1175" alt="Screenshot 2024-04-01 at 16 46 36" src="https://github.com/wso2/api-manager/assets/54719880/fc3a6a8b-1fb7-47ee-bfa4-8167f9abfbe6">

Publisher portal

<img width="1175" alt="Screenshot 2024-04-01 at 16 46 21" src="https://github.com/wso2/api-manager/assets/54719880/ebc5a22d-11a4-41a3-a2d1-52ae39c9a3a8">

### Steps to Reproduce

Prerequisites 
-------------
1. Add below config to deployment.toml file of the fresh pack

[apim.oauth_config]

enable_jwt_for_portals = true

2. Start APIM
3. Login to Management console
4. Navigate to -> Service providers list -> Edit the devportal sp -> Inbound Authentication Configuration -> OAuth/OpenId Connect Configuration ->Edit
5. Check the token issuer

### Affected Component

APIM

### Version

4.3.0

### Relevant Log Output

```shell
ERROR - [introspect] Servlet.service() for servlet [introspect] in context with path [/devportal] threw exception [java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
```

**Comment by chamilaadhi** [comment] 2024-04-01 13:54
@vishmi49 did you add all the configurations mentioned in https://apim.docs.wso2.com/en/4.3.0/install-and-setup/setup/security/securing-api-m-web-portals/#enable-jwt-for-web-portals? From the reproducing steps i could see only one config

**Comment by tharikaGitHub** [comment] 2024-04-01 16:32
Hi All,

The reproducing steps are as follows.

1. Start a fresh default pack without any configuration changes. In this case - APIM 4.3.0-beta.
2. Access the Management Console (/carbon) and create a new tenant, say wso2.com.
3. Access the developer portal and click on "SIGN-IN". (Logging in is not required) This will create a Service Provider for the Devportal App.
4. Access the publisher portal and similarly click on "SIGN-IN". This will create a Service Provider for the Publisher App.
5. If you access both the SP apps corresponding to the 2 portals above, you will see that no Token Issuer is selected. This means by default the token issuer type is "Default".
6. Now shut down the server and configure it for disabling token persistence by adding the below configuration to the deployment.toml.
```
[oauth]
add_tenant_domain_to_access_token = true

[oauth.token_persistence]
enable=false

[oauth.revoked_token_headers_in_response]
enable=false

[[oauth.extensions.token_types]]
name = "JWT"
issuer = "org.wso2.is.key.manager.tokenpersistence.issuer.ExtendedJWTTokenIssuer"

[transport.https.properties]
maxHttpHeaderSize = "12288"

[apim.oauth_config]
enable_jwt_for_portals = true
```
7. Restart the server.
8. Access the Devportal and click on carbon.super from the Tenant selection.
9. Login to the developer portal using the wso2.com tenant's credentials.
10. You will observer the errors mentioned in the description above.

However this is the expected behaviour because the SPs were created before enabling the token persistence configuration. To fix it, we need to follow the steps in the documentation [1] for an existing deployment.

As this is not a bug, I will close the issue.

[1] https://apim.docs.wso2.com/en/4.3.0/install-and-setup/setup/security/securing-api-m-web-portals/#enable-jwt-for-web-portals

Thanks,
Tharika.

**Closed by tharikaGitHub** 2024-04-01 16:32 UTC
Labels: Type/Bug, Severity/Critical, 4.3.0-beta, Affected/APIM-4.3.0, BugFixing
