### ISSUE TITLE
Application subscriptions are not visible in cross tenant devportal

### ISSUE THREAD

**Issue by RusJaI** [wso2/api-manager#2685] opened 2024-03-20 09:16 UTC
### Description

When cross tenant subscription enabled, the published API is visible for all tenants, and API is subscribed by an application of a different tenant at the devportal of API owners domain, the API is visible under Applications -> subscriptions.

(a) But when switched the devportal's domain to the application's tenant domain, API is not visible under Applications -> subscriptions. In APIM 4.0.0, this is visible with links disabled to the API. Is this intended for APIM 4.3.0 ?

(b) Further, the subscription count for an application is always visible as '0' in Applications page.

### Steps to Reproduce

1. Enable cross tenant subscriptions in deployment.toml
2. Publish an api in tenant 1. Select 'visible to all tenants' under subscriptions
3. Login to the devportal as tenant 2, create an application and go to the devportal of 'tenant 1'
4. Subscribe to the API
5. **Go to Applications page. Subscription count is 0**
6. Go to 'Applications' -> Subscriptions
7. **API is visible there**
8. Then switch the dev portal to tenant 2's devportal
9. Go to 'Applications' -> Subscriptions
10. **The subscribed API is not visible there**
11.  **Go to Applications page. Subscription count is 0**

### Affected Component

APIM

### Version

4.3.0-alpha

**Comment by tharikaGitHub** [comment] 2024-03-21 07:22
Seems to be a purposeful revamp. Need to discuss.

**Comment by tharikaGitHub** [comment] 2024-03-25 07:16
As discussed with the team, this is the expected behaviour. Hence closing the issue.

**Closed by tharikaGitHub** 2024-03-25 07:16 UTC
Labels: Type/Bug, Component/APIM, 4.3.0, Affected/APIM-4.3.0, BugFixing
