### ISSUE TITLE
chpasswd not working in MI 4.0.0

### ISSUE THREAD

**Issue by LayaniMal** [wso2/api-manager#2319] opened 2023-12-12 12:53 UTC
### Description

The chpasswd.sh tool is not working properly and it is giving the below error:

```
Error: Could not find or load main class org.wso2.carbon.core.util.PasswordUpdater
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.core.util.PasswordUpdater
```

### Steps to Reproduce

- Install MI 4.0.0 and navigate to <MI_4.0.0_HOME>/bin
- Execute chpasswd.sh script

### Affected Component

MI

### Version

4.0.0

### Relevant Log Output

```shell
sh chpasswd.sh
Buildfile: /home/Documents/CRT/TEST/mi-4.0.0-with-mi-dashboard/wso2mi-4.0.0/bin/build.xml
  [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.

setup:
     [copy] Copying 31 files to /home/Documents/CRT/TEST/mi-4.0.0-with-mi-dashboard/wso2mi-4.0.0/wso2/lib
    [mkdir] Created dir: /home/Documents/CRT/TEST/mi-4.0.0-with-mi-dashboard/wso2mi-4.0.0/wso2/tmp/setup
   [delete] Deleting directory /home/Documents/CRT/TEST/mi-4.0.0-with-mi-dashboard/wso2mi-4.0.0/wso2/tmp/setup
     [move] Moving 29 files to /home/Documents/CRT/TEST/mi-4.0.0-with-mi-dashboard/wso2mi-4.0.0/wso2/lib

BUILD SUCCESSFUL
Total time: 0 seconds
Error: Could not find or load main class org.wso2.carbon.core.util.PasswordUpdater
Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.core.util.PasswordUpdater
```

### Related Issues

https://github.com/wso2/api-manager/issues/2004

### Suggested Labels

MI-4.0.0

**Comment by malakaganga** [comment] 2023-12-21 07:48
Duplicate of: 
https://github.com/wso2/api-manager/issues/2004

**Closed by malakaganga** 2023-12-21 07:48 UTC
Labels: Type/Bug, Missing/Component
