### ISSUE TITLE
API unified search results in an unfiltered list of all existing APIs when searching with names containing spaces

### ISSUE THREAD

**Issue by vishmi49** [wso2/api-manager#2492] opened 2024-02-19 06:59 UTC
### Description

API unified search results in an unfiltered list of all existing APIs when searching with names containing spaces.

<img width="1314" alt="Screenshot 2024-02-19 at 11 58 12" src="https://github.com/wso2/api-manager/assets/54719880/5ee9bfe9-22c8-4c8a-9de0-7df5ac024961">

 When searching a name without space , returns only the matching names with and without spaces.

### Steps to Reproduce

1. Login to the publisher portal 
2. Create an API with  a space in the name
3. Navigate to the landing page
4. Search the exact name

### Affected Component

APIM

### Version

4.3.0

### Environment Details (with versions)

Local Environment

**Comment by tharikaGitHub** [comment] 2024-03-21 14:53
Closing as the issue is fixed.

**Closed by tharikaGitHub** 2024-03-21 14:53 UTC
Labels: Type/Bug, Component/APIM, 4.3.0, 4.3.0-alpha, BugFixing
