### ISSUE TITLE
Cannot block subscription for applications created by users with "-" hyphen character in the user name.

### ISSUE THREAD

**Issue by inuri2000** [wso2/api-manager#934] opened 2022-11-15 05:56 UTC
### Description

Hi Team,

**Issue Description:**
Cannot block applications which were created by users who has a hyphen (-) in their username. 

Thankyou,
Inuri.

### Steps to Reproduce

Create a user with hyphen in the username. (inuri-test)
Login to developer portal and create an application (TestApp)
Subscribe to an API
Go to the publisher and try to block the subscription.

### Affected Component

APIM

### Version

3.2.0

### Relevant Log Output

```shell
[2022-11-10 19:27:59,219] INFO - CarbonUIServiceComponent API Publisher Default Context : https://localhost:9443/publisher [2022-11-10 19:28:19,085] ERROR - SubscriptionsApiServiceImpl Error while blocking the subscription d9abbe73-0054-42ae-93b8-9b4613f836f1 org.wso2.carbon.apimgt.api.APIManagementException: Couldn't Save Subscription Block Condition Due to Invalid Application name test-inuApp from Application Owner inu at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.addBlockConditions_aroundBody584(ApiMgtDAO.java:12635) ~[org.wso2.carbon.apimgt.impl_6.7.206.365.jar:?]
```

### Suggested Labels

product/apim

**Comment by Tharsanan1** [comment] 2022-12-08 04:02
Could not reproduce the issue on the latest. Created public test pr and merged: https://github.com/wso2/product-apim/pull/13010

**Closed by Tharsanan1** 2022-12-08 04:02 UTC
Labels: Type/Bug, Priority/Normal, Affected/APIM-3.2.0, U2/WUM
