### ISSUE TITLE
Remove Hazelcast from carbon-analytics-common

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/api-manager#1028] opened 2022-11-25 03:18 UTC
### Description

After the kernel upgrade done via [1], the server was not starting and hangs at one point. When running the server with `sh api-manager.sh -DosgiConsole -Dequinox.ds.print=true` by enabling additional error log output, an error was shown as below.

![image](https://user-images.githubusercontent.com/25246848/203893058-e49974e2-6b9d-4f73-99df-3d6567a0fa32.png)

The reason for the above error is, even though we remove Hazelcast from Carbon Kernel 4.8.0-m2 via [2], still, the carbon-analytics-common requires it. Hence, we need to remove Hazelcast from there too.

[1] https://github.com/wso2/api-manager/issues/973
[2] https://github.com/wso2/carbon-kernel/pull/3440

#### Sub Tasks : 

- [ ] https://github.com/wso2/api-manager/issues/1041
- [ ] https://github.com/wso2/api-manager/issues/1043
- [ ] https://github.com/wso2/api-manager/issues/1059
- [ ] https://github.com/wso2/api-manager/issues/1060

### Affected Component

APIM

### Version

4.2.0

### Related Issues

https://github.com/wso2/api-manager/issues/973

**Comment by piyumaldk** [comment] 2022-11-25 09:59
Removed the "Distributed" and "HA" components from Carbon-Commons-Analytics since they are not used in current APIM as discussed. Then Removed the  Hazelcast  usage from the repository since HA components are already removed.

**Comment by piyumaldk** [comment] 2022-11-25 10:01
Build Carbon-Commons-Analytics with tests successfully.

**Comment by piyumaldk** [comment] 2022-11-25 10:07
While testing with Carbon-APIMGT and Product-APIM, noticed that product APIM build failed due to a missing requirement. Tried updating Carbon-Event-Processing with Carbon-Commons-Analytics and still the issue was there.

**Comment by piyumaldk** [comment] 2022-11-25 10:12
Got the v5.2.48 tag of Carbon-Commons-Analytics and Cherry-Pick the changes to it and built the product without tests. This time, build was a success. Run the product and manually tested with a simple API creation and try out.

**Comment by piyumaldk** [comment] 2022-11-25 10:16
Ran the Carbon-APIMGT locally with unit tests. Results were successful.

**Comment by piyumaldk** [comment] 2022-11-25 17:27
Ran the Product-APIM locally with integration tests. Results were successful.

**Comment by piyumaldk** [comment] 2022-11-29 04:54
Cut a new branch as 5.3.x in Carbon-Analytics-Commons. Then changed the POM versions of 5.3.x. After that, cherry-picked the changes done to Carbon-Analytics-Commons 5.2.48 tag to the 5.3.x version.

**Comment by piyumaldk** [comment] 2022-11-29 12:15
Created a distributed setup for APIM locally to test Carbon-Analytics-Commons 5.3.x and Kernel M2. Noticed that there is an error with "org.wso2.carbon.ntask.core_4.9.0" when running the Gateway.

**Comment by piyumaldk** [comment] 2022-11-30 07:15
Identified that the problem is coming because HazelCast removal is not merged in carbon.commons. Since we are no longer using 4.7.x of carbon.commons in our product, cherry-picked the changes to 4.9.x. 4.9.x has been created specifically to use in our product.

**Comment by piyumaldk** [comment] 2022-11-30 08:13
When trying to setup a distributed setup locally with new carbon.commons and carbon.analytics.commons versions, apim-product build failed due to 2 errors. Identified as the 1st error was coming because of rebasing the product with the master, and solved it by reverting the specific commit from local branch.

**Comment by piyumaldk** [comment] 2022-11-30 11:49
Identified as the 2nd error was coming because event-processor has an earlier version of "carbon.analytics.commons". Problem has occurred because in APIM, we have moved "carbon.analytics.commons" from 5.2.x to 5.3.x. After testing event-processor with the "carbon.analytics.commons" 5.3.x, problem with APIM was solved. But in order to add that version to event-processor, some code segments will have to be changed since "carbon.analytics.commons" 5.3.x no longer has Distributed and HA types.

**Comment by piyumaldk** [comment] 2022-12-01 04:52
As a solution to the 2nd problem, added HA and Distributed variables to the carbon.analytics.commons 5.3.x without adding the content of HA and Distributed again.

**Comment by piyumaldk** [comment] 2022-12-01 08:00
Bumped the carbon.analytics.commons version in the carbon.event.processing so new changes done to carbon.analytics.commons will be effective and solve the [2nd issue](https://github.com/wso2/api-manager/issues/1060). With that, closing this issue since HazelCast removal in carbon.analytics.commons is completed.

**Closed by piyumaldk** 2022-12-01 08:00 UTC
Labels: Type/Task, Priority/High, Component/APIM, Missing/Component, 4.2.0-alpha
