### ISSUE TITLE
Custom search queries failure if spaces include

### ISSUE THREAD

**Issue by shnrndk** [wso2/api-manager#2462] opened 2024-02-08 04:19 UTC
### Description

After introduction of the feature PR[1] we have included this logic if the query starts with name or description then we replace all the spaces with `%20` string. This was happened to pizzashackapi default search query as well. But we have added condition to check if it is not equal to default query then only it will check the second condition. 

Failed sample custom query: `name:testApi version:1.0 context:testApi`

[1] https://github.com/wso2/carbon-apimgt/pull/12200

### Steps to Reproduce

1.) Create api called testApi.
2.) Invoke this rest api
` https://localhost:9443/api/am/publisher/v4/search?limit=1&offset=0&query=name%3AtestApi%20version%3A1.0%20context%3AtestApi`

### Affected Component

APIM

### Version

APIM 4.3.0

**Comment by tharikaGitHub** [comment] 2024-03-21 14:55
Closing as the issue is fixed.

**Closed by tharikaGitHub** 2024-03-21 14:55 UTC
Labels: Type/Bug, Component/APIM, 4.3.0, 4.3.0-alpha, BugFixing
